AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'gemfiles/vendor/**/*'

Style/HashSyntax:
  EnforcedStyle: hash_rockets
  SupportedStyles:
    - hash_rockets

Style/SymbolArray:
  Enabled: false # %i[] syntax isn't 1.9.x compatible

Metrics/LineLength:
  Max: 1000

Style/DoubleNegation:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/EachWithObject:
  Enabled: false
